services:
  henriklindgrencom:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    #user: "1000:1000"
    networks:
      - npm_proxy

networks:
  npm_proxy:
    external: true